In [2]:
import os
import pandas as pd
from faker import Faker

fake = Faker('ko_KR')

#Faker로 주소 생성
def generate_fake_addresses(num=10000):
    addresses = [fake.address() for _ in range(num)]
    return addresses

#Faker주소 생성저장
def save_to_csv(data, filename='fake_addresses.csv'):
    df = pd.DataFrame(data, columns=['Address'])
    df.to_csv(filename, index=False, encoding='cp949')

#실제주소들 merge
def merge_csv_files():
    file_list = [filename for filename in os.listdir() if filename.endswith(".csv")]
    merged_data = pd.DataFrame()
    for file in file_list:
        data = pd.read_csv(file, encoding='cp949')
        merged_data = pd.concat([merged_data, data])
    return merged_data

#실제주소 도로명 주소로 추출
def generate_road_addresses(row):
    city = row['city']
    borough = row['borough']
    road_name = row['road_name']
    road_number = row['road_number']
    road_address = f"{city} {borough} {road_name}{road_number}번길"
    return road_address



print(merged_df.head())
    
fake_addresses = generate_fake_addresses(10000)
save_to_csv(fake_addresses)

    city borough town old postal code road_name  road_number  postcode
0  부산광역시      중구  영주동           60-18      초량상로            1     48910
1  부산광역시      중구  영주동           60-23      초량상로            1     48910
2  부산광역시      중구  영주동           60-48      초량상로            5     48910
3  부산광역시      중구  영주동            52-1      초량상로            6     48911
4  부산광역시      중구  영주동             8-2      초량상로            9     48906

In [6]:
fake_addresses = generate_fake_addresses(10)

split_addresses = [address.split() for address in fake_addresses]

# 분리된 주소 출력
for split_address in split_addresses:
    print(split_address)

['부산광역시', '송파구', '학동81가']
['서울특별시', '영등포구', '역삼길', '(정순우마을)']
['광주광역시', '강북구', '논현52로', '(춘자권박읍)']
['인천광역시', '성북구', '테헤란931가', '(지후안김동)']
['부산광역시', '양천구', '영동대31거리', '(정희이마을)']
['경상남도', '춘천시', '오금39거리']
['울산광역시', '노원구', '학동20로']
['충청북도', '정선군', '개포2거리', '(지혜김면)']
['인천광역시', '성동구', '도산대33가', '(영순송리)']
['충청남도', '춘천시', '봉은사733로']

In [23]:
fake_addresses = generate_fake_addresses(10)

split_addresses = [address.split() for address in fake_addresses]

# 분리된 주소 출력
for split_address in split_addresses:
    city = split_address[0]
    split_address_1 = split_address[1]
    
    print(split_address)
    matching_rows = merged_df[(merged_df['city'] == city) & ((merged_df['borough'] == split_address_1) | (merged_df['town'] == split_address_1))]

    print(matching_rows)

['경기도', '증평군', '학동985길']
Empty DataFrame
Columns: [city, borough, town, old postal code, road_name, road_number, postcode]
Index: []
['인천광역시', '성동구', '강남대267로']
Empty DataFrame
Columns: [city, borough, town, old postal code, road_name, road_number, postcode]
Index: []
['광주광역시', '노원구', '서초대길']
Empty DataFrame
Columns: [city, borough, town, old postal code, road_name, road_number, postcode]
Index: []
['제주특별자치도', '수원시', '팔달구', '가락424로']
Empty DataFrame
Columns: [city, borough, town, old postal code, road_name, road_number, postcode]
Index: []
['강원도', '논산시', '도산대로', '(재호조면)']
Empty DataFrame
Columns: [city, borough, town, old postal code, road_name, road_number, postcode]
Index: []
['대구광역시', '도봉구', '석촌호수거리', '(민수김이리)']
Empty DataFrame
Columns: [city, borough, town, old postal code, road_name, road_number, postcode]
Index: []
['광주광역시', '노원구', '석촌호수0거리']
Empty DataFrame
Columns: [city, borough, town, old postal code, road_name, road_number, postcode]
Index: []
['경기도', '광명시', '논현거리', '(재호박면)']
       city borough town old postal code road_name  road_number  postcode
174480  경기도     광명시  광명동           33-72       오리로          908     14222
174481  경기도     광명시  광명동           33-70       오리로          912     14222
174482  경기도     광명시  광명동           33-68       오리로          914     14222
174483  경기도     광명시  광명동           33-79       오리로          916     14222
174484  경기도     광명시  광명동           33-66       오리로          916     14222
...     ...     ...  ...             ...       ...          ...       ...
184775  경기도     광명시  옥길동           359-2       식곡길           33     14298
184776  경기도     광명시  옥길동           356-1       식곡길           33     14298
184777  경기도     광명시  옥길동           358-1       식곡길           34     14298
184778  경기도     광명시  옥길동           359-1       식곡길           37     14298
184779  경기도     광명시  옥길동           410-8       식곡길           39     14298

[10300 rows x 7 columns]
['충청남도', '하남시', '가락313가', '(예지최이면)']
Empty DataFrame
Columns: [city, borough, town, old postal code, road_name, road_number, postcode]
Index: []
['경상남도', '안성시', '역삼1거리', '(현주윤김리)']
Empty DataFrame
Columns: [city, borough, town, old postal code, road_name, road_number, postcode]
Index: []

In [9]:
merged_df

         city borough town old postal code road_name  road_number  postcode
0       부산광역시      중구  영주동           60-18      초량상로            1     48910
1       부산광역시      중구  영주동           60-23      초량상로            1     48910
2       부산광역시      중구  영주동           60-48      초량상로            5     48910
3       부산광역시      중구  영주동            52-1      초량상로            6     48911
4       부산광역시      중구  영주동             8-2      초량상로            9     48906
...       ...     ...  ...             ...       ...          ...       ...
104005  울산광역시     울주군  삼동면           248-1       금곡길          292     44956
104006  울산광역시     울주군  삼동면           188-0       금곡길          301     44956
104007  울산광역시     울주군  삼동면           192-3       금곡길          301     44956
104008  울산광역시     울주군  삼동면           193-0       금곡길          301     44956
104009  울산광역시     울주군  삼동면           192-4       금곡길          301     44956

[6329413 rows x 7 columns]

In [ ]:
import pandas as pd
from faker import Faker

fake = Faker('ko_KR')

def generate_fake_addresses(num=10000):
    addresses = [fake.address() for _ in range(num)]
    return addresses

def save_to_csv(data, filename='fake_addresses.csv'):
    df = pd.DataFrame(data, columns=['Address'])
    df.to_csv(filename, index=False, encoding='cp949')

def load_real_addresses(directory='', filename='merged_result.csv'):
    df = pd.read_csv(directory + filename, encoding='cp949')
    cities = set(df['city'].unique())
    boroughs = {city: set(df[df['city'] == city]['borough'].unique()) for city in cities}
    return cities, boroughs

def validate_fake_address(fake_address, cities, boroughs):
    parts = fake_address.split(' ')
    city = parts[0]
    borough = parts[1]

    if city not in cities:
        return False
    elif borough not in boroughs.get(city, set()):
        return False
    else:
        return True

if __name__ == "__main__":
    fake_addresses = generate_fake_addresses(10000)
    save_to_csv(fake_addresses)

    cities, boroughs = load_real_addresses()
    fake_addresses_df = pd.read_csv('fake_addresses.csv',encoding='cp949')
    
    mismatches = fake_addresses_df['Address'].apply(lambda x: not validate_fake_address(x, cities, boroughs))
    mismatch_count = mismatches.sum()

    print(f"Number of mismatched addresses: {mismatch_count} out of {len(fake_addresses_df)}")